### PR TITLE
refactor the driver and stop attempting to read light feedback

### PR DESCRIPTION
**Pull request by rafaelsaback**
Diego: "They don't send any data when in a multi-drop configuration"

This is a fix to make the driver work.

### CODE REVIEW

**Comment by doudou** [comment]
> This is a fix to make the driver work.

Not a 'fix', a workaround to have it "working" on Flat Fish when in a multi-drop configuration.

I am very concerned about this change, because it truly means that we have no way to check that the lamps are responding to our commands. Is Diego's comment based on actual documentation from the manufacturer, or is it a guess because we don't receive anything (which would be due to other factors, as e.g. having a poorly handled half-duplex RS485 connection)

**Comment by rafaelsaback** [comment]
> Not a 'fix', a workaround to have it "working" on Flat Fish when in a multi-drop configuration.

:+1:

> Is Diego's comment based on actual documentation from the manufacturer, or is it a guess because we don't receive anything (which would be due to other factors, as e.g. having a poorly handled half-duplex RS485 connection)

I'd guess it's based on experiments. @dbcesar is on vacations now, but when he's back he can clarify this. I'd just leave this PR hanging for the next 3 weeks and then Diego can update us about it so we can decide the best solution for this. Fine?

**Comment by doudou** [comment]
> Fine?

Sounds reasonable. In that case, I would be OK with having it on a `workaround_rs485_flatfish` branch and pick the branch in the buildconf.

**Comment by dbcesar** [comment]
> I am very concerned about this change, because it truly means that we have no way to check that the lamps are responding to our commands. Is Diego's comment based on actual documentation from the manufacturer, or is it a guess because we don't receive anything (which would be due to other factors, as e.g. having a poorly handled half-duplex RS485 connection)

@doudou AFAIK it's a sensor limitation, it can't work in a full duplex configuration. So it works fine when a single-drop, but it doesn't when a multi-drop configuration. What would be better? To remove the listening on the master or to keep it there and create a branch "work_on_multidrop", or even create a property where you can set which configuration you are?

**Comment by doudou** [comment]
> it can't work in a full duplex configuration

This sentence implies that it can work in half-duplex. I'm assuming that by "multidrop" you mean "with more than one device on the bus", which can very well work in half-duplex as long as it the bus is arbitrated by a master.

**Comment by dbcesar** [comment]
> which can very well work in half-duplex as long as it the bus is arbitrated by a master.

Yes.

I have to test it again, but I think it works well when we try to communicate with each lamp by turn. Currently, there is a broadcast address that allows to control all lamps with a single command, in that case all lamps reply at the same time and for that reason the message is incomprehensible. So I think that we have to go in the way of change the driver in order to control the lamp individually and avoid to use the broadcast address. Is that?

**Comment by doudou** [comment]
> Is that?

If it works, it would be a lot better, yes.

**Comment by rafaelsaback** [comment]
@dbcesar can we close this PR?

**Comment by dbcesar** [comment]
@rbritotl is still looking on the camera behavior. I don't know what it right to do here, just close or merge.

**Comment by romulogcerqueira** [comment]
@doudou , fixed light level value.

**Comment by romulogcerqueira** [comment]
Already tested on FlatFish. If no more comments, this is ready to merge.

**Comment by rbritotl** [comment]
Agreed. Even after fixing Rx jumper on the SMB, no feedback was received from the LEDs, so the driver shouldn't attempt to read after writing instructions to the LEDs. This PR adresses this very issue properly.

**Pull request merged**
